PIPELINE_SOURCES = [

# REAL ESTATE SOURCES
{"name": "zillow_feed", "url": "https://api.source1.com/zillow"},
{"name": "redfin_feed", "url": "https://api.source2.com/redfin"},
{"name": "auction_feed", "url": "https://api.source3.com/auction"},
{"name": "probate_feed", "url": "https://api.source4.com/probate"},
{"name": "tax_delinquent_feed", "url": "https://api.source5.com/tax"},
{"name": "vacant_property_feed", "url": "https://api.source6.com/vacant"},
{"name": "foreclosure_feed", "url": "https://api.source7.com/foreclosure"},
{"name": "offmarket_feed", "url": "https://api.source8.com/offmarket"},
{"name": "investor_property_feed", "url": "https://api.source9.com/investor"},
{"name": "distressed_property_feed", "url": "https://api.source10.com/distressed"},

# VEHICLE INVENTORY
{"name": "autotrader_feed", "url": "https://api.source11.com/autotrader"},
{"name": "cars_feed", "url": "https://api.source12.com/cars"},
{"name": "dealer_inventory_feed", "url": "https://api.source13.com/dealer"},
{"name": "auction_vehicle_feed", "url": "https://api.source14.com/vehicle_auction"},
{"name": "tradein_feed", "url": "https://api.source15.com/tradein"},
{"name": "used_car_feed", "url": "https://api.source16.com/usedcars"},
{"name": "new_car_feed", "url": "https://api.source17.com/newcars"},
{"name": "luxury_vehicle_feed", "url": "https://api.source18.com/luxury"},
{"name": "truck_inventory_feed", "url": "https://api.source19.com/trucks"},
{"name": "fleet_vehicle_feed", "url": "https://api.source20.com/fleet"},

# LEAD GENERATION
{"name": "facebook_marketplace_leads", "url": "https://api.source21.com/facebook_marketplace"},
{"name": "finance_leads", "url": "https://api.source22.com/finance"},
{"name": "investor_network_leads", "url": "https://api.source23.com/investor"},
{"name": "referral_leads", "url": "https://api.source24.com/referral"},
{"name": "website_form_leads", "url": "https://api.source25.com/forms"},
{"name": "chatbot_leads", "url": "https://api.source26.com/chatbot"},
{"name": "sms_leads", "url": "https://api.source27.com/sms"},
{"name": "email_campaign_leads", "url": "https://api.source28.com/email"},
{"name": "landing_page_leads", "url": "https://api.source29.com/landing"},
{"name": "affiliate_leads", "url": "https://api.source30.com/affiliate"},

# MARKETING DATA
{"name": "facebook_ads_data", "url": "https://api.source31.com/facebook_ads"},
{"name": "google_ads_data", "url": "https://api.source32.com/google_ads"},
{"name": "tiktok_ads_data", "url": "https://api.source33.com/tiktok_ads"},
{"name": "instagram_ads_data", "url": "https://api.source34.com/instagram_ads"},
{"name": "youtube_ads_data", "url": "https://api.source35.com/youtube_ads"},
{"name": "seo_leads", "url": "https://api.source36.com/seo"},
{"name": "ppc_leads", "url": "https://api.source37.com/ppc"},
{"name": "display_ads_data", "url": "https://api.source38.com/display_ads"},
{"name": "retargeting_data", "url": "https://api.source39.com/retargeting"},
{"name": "crm_marketing_data", "url": "https://api.source40.com/crm_marketing"},

# WHOLESALE DEAL SOURCES
{"name": "wholesale_feed_1", "url": "https://api.source41.com/wholesale1"},
{"name": "wholesale_feed_2", "url": "https://api.source42.com/wholesale2"},
{"name": "wholesale_feed_3", "url": "https://api.source43.com/wholesale3"},
{"name": "wholesale_feed_4", "url": "https://api.source44.com/wholesale4"},
{"name": "wholesale_feed_5", "url": "https://api.source45.com/wholesale5"},
{"name": "wholesale_feed_6", "url": "https://api.source46.com/wholesale6"},
{"name": "wholesale_feed_7", "url": "https://api.source47.com/wholesale7"},
{"name": "wholesale_feed_8", "url": "https://api.source48.com/wholesale8"},
{"name": "wholesale_feed_9", "url": "https://api.source49.com/wholesale9"},
{"name": "wholesale_feed_10", "url": "https://api.source50.com/wholesale10"},

# CUSTOM DATA SOURCES 51-100
{"name": "custom_51", "url": "https://api.source51.com/data"},
{"name": "custom_52", "url": "https://api.source52.com/data"},
{"name": "custom_53", "url": "https://api.source53.com/data"},
{"name": "custom_54", "url": "https://api.source54.com/data"},
{"name": "custom_55", "url": "https://api.source55.com/data"},
{"name": "custom_56", "url": "https://api.source56.com/data"},
{"name": "custom_57", "url": "https://api.source57.com/data"},
{"name": "custom_58", "url": "https://api.source58.com/data"},
{"name": "custom_59", "url": "https://api.source59.com/data"},
{"name": "custom_60", "url": "https://api.source60.com/data"},
{"name": "custom_61", "url": "https://api.source61.com/data"},
{"name": "custom_62", "url": "https://api.source62.com/data"},
{"name": "custom_63", "url": "https://api.source63.com/data"},
{"name": "custom_64", "url": "https://api.source64.com/data"},
{"name": "custom_65", "url": "https://api.source65.com/data"},
{"name": "custom_66", "url": "https://api.source66.com/data"},
{"name": "custom_67", "url": "https://api.source67.com/data"},
{"name": "custom_68", "url": "https://api.source68.com/data"},
{"name": "custom_69", "url": "https://api.source69.com/data"},
{"name": "custom_70", "url": "https://api.source70.com/data"},
{"name": "custom_71", "url": "https://api.source71.com/data"},
{"name": "custom_72", "url": "https://api.source72.com/data"},
{"name": "custom_73", "url": "https://api.source73.com/data"},
{"name": "custom_74", "url": "https://api.source74.com/data"},
{"name": "custom_75", "url": "https://api.source75.com/data"},
{"name": "custom_76", "url": "https://api.source76.com/data"},
{"name": "custom_77", "url": "https://api.source77.com/data"},
{"name": "custom_78", "url": "https://api.source78.com/data"},
{"name": "custom_79", "url": "https://api.source79.com/data"},
{"name": "custom_80", "url": "https://api.source80.com/data"},
{"name": "custom_81", "url": "https://api.source81.com/data"},
{"name": "custom_82", "url": "https://api.source82.com/data"},
{"name": "custom_83", "url": "https://api.source83.com/data"},
{"name": "custom_84", "url": "https://api.source84.com/data"},
{"name": "custom_85", "url": "https://api.source85.com/data"},
{"name": "custom_86", "url": "https://api.source86.com/data"},
{"name": "custom_87", "url": "https://api.source87.com/data"},
{"name": "custom_88", "url": "https://api.source88.com/data"},
{"name": "custom_89", "url": "https://api.source89.com/data"},
{"name": "custom_90", "url": "https://api.source90.com/data"},
{"name": "custom_91", "url": "https://api.source91.com/data"},
{"name": "custom_92", "url": "https://api.source92.com/data"},
{"name": "custom_93", "url": "https://api.source93.com/data"},
{"name": "custom_94", "url": "https://api.source94.com/data"},
{"name": "custom_95", "url": "https://api.source95.com/data"},
{"name": "custom_96", "url": "https://api.source96.com/data"},
{"name": "custom_97", "url": "https://api.source97.com/data"},
{"name": "custom_98", "url": "https://api.source98.com/data"},
{"name": "custom_99", "url": "https://api.source99.com/data"},
{"name": "custom_100", "url": "https://api.source100.com/data"}

]
